import type { ActivityItem, Combatant } from '#/types/dm-shell'

export const activities: ActivityItem[] = [
  { id: 'rules', label: 'Rules', icon: 'book-open' },
  { id: 'monsters', label: 'Monsters', icon: 'skull' },
  { id: 'spells', label: 'Spells', icon: 'wand-2' },
  { id: 'equipment', label: 'Equipment', icon: 'backpack' },
  { id: 'magic-items', label: 'Magic items', icon: 'sparkles' },
  { id: 'classes', label: 'Classes', icon: 'graduation-cap' },
  { id: 'subclasses', label: 'Subclasses', icon: 'layers' },
  { id: 'races', label: 'Races', icon: 'dna' },
  { id: 'traits', label: 'Traits', icon: 'fingerprint' },
  { id: 'alignments', label: 'Alignments', icon: 'compass' },
  { id: 'languages', label: 'Languages', icon: 'languages' },
  { id: 'damage-types', label: 'Damage types', icon: 'flame' },
  { id: 'characters', label: 'Player characters', icon: 'users' },
  { id: 'campaign', label: 'Campaign', icon: 'map' },
  { id: 'audio', label: 'Audio', icon: 'music' },
]

export const combatants: Combatant[] = [
  {
    id: 'goblin-1',
    kind: 'monster',
    sourceIndex: 'goblin',
    name: 'Goblin 1',
    initiative: 16,
    initiativeDetail: '13 +3 (Dex) = 16',
    currentHp: 4,
    maxHp: 7,
    tempHp: 0,
    conditions: [{ name: 'Poisoned', duration: 2 }],
    resources: [],
    hasActedThisRound: false,
  },
  {
    id: 'goblin-2',
    kind: 'monster',
    sourceIndex: 'goblin',
    name: 'Goblin 2',
    initiative: 12,
    initiativeDetail: '9 +3 (Dex) = 12',
    currentHp: 7,
    maxHp: 7,
    tempHp: 0,
    conditions: [],
    resources: [],
    hasActedThisRound: false,
  },
  {
    id: 'lair-action',
    kind: 'lair-action',
    name: 'Lair action',
    initiative: 11,
    currentHp: 0,
    maxHp: 0,
    tempHp: 0,
    conditions: [],
    resources: [],
    hasActedThisRound: false,
  },
  {
    id: 'mira',
    kind: 'pc',
    name: 'Mira',
    initiative: 9,
    currentHp: 22,
    maxHp: 22,
    tempHp: 0,
    conditions: [],
    resources: [],
    hasActedThisRound: false,
  },
  {
    id: 'goblin-3',
    kind: 'monster',
    sourceIndex: 'goblin',
    name: 'Goblin 3',
    initiative: 6,
    initiativeDetail: '3 +3 (Dex) = 6',
    currentHp: 0,
    maxHp: 7,
    tempHp: 0,
    conditions: [],
    resources: [],
    hasActedThisRound: false,
  },
]
